fix: fix .travis.yml error
$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
Error: python 3.6.5_1 is already installed
To upgrade to 3.7.4_1, run `brew upgrade python`.
The command "if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi" failed and exited with 1 during .